export enum ErrorCode {
  // Resource errors
  INVALID_ID = 'INVALID_ID',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  DUPLICATE_ENTRY = 'DUPLICATE_ENTRY',
  INVALID_INPUT = 'INVALID_INPUT',
  // Authentication errors
  EMAIL_REQUIRED = 'EMAIL_REQUIRED',
  PASSWORD_REQUIRED = 'PASSWORD_REQUIRED',
  INVALID_EMAIL = 'INVALID_EMAIL',
  INVALID_EMAIL_FORMAT = 'INVALID_EMAIL_FORMAT',
  INVALID_EMAIL_PWD = 'INVALID_EMAIL_PWD',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  ALREADY_VERIFIED = 'USER_ALREADY_VERIFIED',

  // Authorization errors
  UNAUTHORIZED = 'UNAUTHORIZED',
  UNAUTHORIZED_USER = 'UNAUTHORIZED_USER',
  FORBIDDEN = 'FORBIDDEN',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  INVALID_EXPIRED_TOKEN = 'INVALID_EXPIRED_TOKEN',
  USER_DEACTIVATED = 'USER_DEACTIVATED',
  USER_ACTIVATED = 'USER_ACTIVATED',
  CANNOT_DEACTIVATE_LOGGED_IN_USER = 'CANNOT_DEACTIVATE_LOGGED_IN_USER',
  CANNOT_DELETE_LOGGED_IN_USER = 'CANNOT_DELETE_LOGGED_IN_USER',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',

  // Validation errors
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  // Server errors
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

  RESOURCE_ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS',
}
