export const SUCCESS_MESSAGE = {
  CREATED: 'The Record has been created successfully',
  UPDATED: 'The Record has been updated successfully',
  DELETED: 'The Record has been deleted successfully',
  PASSWORD_UPDATE_SUCCESS: 'Password updated successfully',
  EMAIL_VERIFICATION_SENT: 'Email verification mail sent successfully',
  EMAIL_VERIFIED_SUCCESS: 'Email verified successfully',
  USER_ACTIVATE_SUCCESS: 'User account activated successfully',
  USER_DEACTIVATE_SUCCESS: 'User account deactivated successfully',
  LOGIN_SUCCESS: 'Login successful',
  TOKEN_REFRESH_SUCCESS: 'Token refreshed successfully',
  LOGOUT_SUCCESS: 'Logged out successfully',
  PASSWORD_RESET_EMAIL_SENT: 'Password reset email sent successfully',
} as const;

export const ERROR_MESSAGE = {
  CANNOT_DEACTIVATE_LOGGED_IN_USER: 'You cannot deactivate your own account',
  CANNOT_DELETE_LOGGED_IN_USER: 'You cannot delete your own account',
  INVALID_ID: 'Invalid Id provided',
  EMPTY_UPDATE_OBJECT: 'please provide field(s) to update',
  EMAIL_REQUIRED: 'Email is required',
  USER_NOT_FOUND: 'User not found',
  USER_ALREADY_EXIST: 'User already exist',
  USER_UNVERIFIED: 'Kindly click the link sent to your email to verify your account',
  ERROR_VERIFICATION_MAIL: 'An error occurred sending user verification email',
  USER_ALREADY_VERIFIED: 'User account is already verified',
  CURRENT_PASSWORD_INCORRECT: 'Current Password Incorrect',
  NEW_PASSWORD_SAME_AS_CURRENT:
    'Cannot use old password as new password. Please choose a different password.',
  INVALID_EXPIRED_TOKEN: 'Invalid or expired token provided',
  AN_ERROR_OCCURRED: 'An error occurred while processing request',
  MAX_UNSUCCESSFUL_LOGIN_REACHED: 'Too many unsuccessful login attempts, please try again later',
  INVALID_EMAIL_PWD: 'Invalid email or password',
  PASSWORD_RESET_REQUIRED:
    'Password reset required. Check your email for reset instructions before logging in.',
  USER_DEACTIVATED: 'This user account has been deactivated. Please contact support',
  INVALID_TOKEN: 'Invalid token provided',
  UNAUTHORIZED: 'Access Denied. Unauthorized to access resource',
  TOKEN_EXPIRED: 'Token expired',
  ROLE_MISMATCH: 'Role does not match role needed to access resource',
  UNAUTHORIZED_USER: 'Request is been made by an unauthorized user',
  USER_ALREADY_DEACTIVATED: 'This user account is already deactivated',
  USER_ALREADY_ACTIVE: 'This user account is already active',
  REQUEST_TIMEOUT:
    'The request timed out. Please check your internet connection or try again later.',
  SERVICE_UNAVAILABLE: 'The service is temporarily unavailable. Please try again later.',
  INTERNAL_SERVER_ERROR: 'Internal Server Error',
  TOO_MANY_REQUESTS: 'Too many requests, please try again later',
  NO_FIELDS_TO_UPDATE: 'No fields provided to update',
  INVALID_CURRENT_PASSWORD: 'Current password is incorrect',
  PROPERTY_NOT_FOUND: 'Property not found',
  INVALID_FILE_TYPE: 'Unsupported file type',
} as const;
